name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies and Build
      run: |
        cd frontend
        npm install
        npm run build

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend/build

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies and Test
      run: |
        cd backend
        pip install -r requirements.txt
        pytest test_app.py

    - name: Upload Dockerized Backend
      run: |
        docker build -t <your-dockerhub-username>/backend:latest ./backend
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push <your-dockerhub-username>/backend:latest

  deploy-k8s:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy Kubernetes Config
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
